import { Component } from '@angular/core'; // Autogenerated for components
import { CommonModule } from '@angular/common'; 

@Component({
  selector: 'app-header',
  standalone: true,
  template: `
    <header style="padding: 1rem; text-align: center;">
      <img src="assets/theBeaconLogo4K.png" alt="The Beacon Logo" style="height: 60px;" />
    </header>
  `,
  styles: []
})
export class HeaderComponent {}
